apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
  namespace: default
spec:
  annotationCheck: 'false'
  engineState: 'active'
  chaosServiceAccount: ec2-terminate-sa
  monitoring: false
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: ec2-terminate
      spec:
        components:
          env: 
           - name: TOTAL_CHAOS_DURATION
             value: DURATION
           - name: EC2_INSTANCE_ID
             value: 'i-0653cb7da098fa3ae'
           - name: REGION
             value: 'ap-south-1'
