apiVersion: v1
kind: Secret
metadata:
   name: cloud-secret
type: Opaque
stringData:
  cloud_config.yml: |-
         [default]
         aws_access_key_id = AKIAX56L2G74EZJ4YGXF
         aws_secret_access_key = 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
         region = ap-south-1
