import subprocess,time

result = subprocess.run(['minikube','start'])
print (result)
time.sleep(2)
result = subprocess.run(['minikube','status'])
print (result)
result = subprocess.run(['kubectl', 'apply', '-f','https://litmuschaos.github.io/litmus/litmus-operator-v1.13.8.yaml'])
print (result)
result = subprocess.run(['kubectl', 'apply', '-f','https://hub.litmuschaos.io/api/chaos/1.13.8?file=charts/kube-aws/ec2-terminate-by-id/experiment.yaml'])
print (result)
result = subprocess.run(['kubectl', 'apply', '-f','secrets.yml'])
print (result)
result = subprocess.run(['kubectl', 'apply', '-f','rbac.yml'])
print (result)
result = subprocess.run(['kubectl', 'apply', '-f', 'engine.yml'])
print (result)
time.sleep(120)
result = subprocess.run(['minikube','stop'])
print (result)
